### ISSUE TITLE
PPocrlabel windows 批量自动标注图片时报错

### ISSUE THREAD

**Issue by Keven-Don** [PFCCLab/PPOCRLabel#107]
Traceback (most recent call last):
  File "d:\dev_soft\Anaconda3\envs\ppocr\Lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 43, in run
    self.result_dic = self.ocr.ocr(Imgpath, cls=True, det=True)[0]
  File "D:\dev_soft\Anaconda3\envs\ppocr\lib\site-packages\paddleocr\paddleocr.py", line 760, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
  File "D:\dev_soft\Anaconda3\envs\ppocr\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 109, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "D:\dev_soft\Anaconda3\envs\ppocr\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 396, in __call__
    dt_boxes, elapse = self.predict(img)
  File "D:\dev_soft\Anaconda3\envs\ppocr\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 255, in predict
    self.predictor.run()
RuntimeError: could not create a primitive
总是跑一半就这样子，windowscpu

**Comment by BotAndyGao** [comment]
paddlepaddle版本和PPOCRLabel版本，自动标注目录有多少图片，请提供这些信息
