### ISSUE TITLE
'utf-8' codec can't decode byte 0xc3 in position 3044: invalid continuation byte

### ISSUE THREAD

**Issue by monkeycc** [PFCCLab/PPOCRLabel#21]
```
 PPOCRLabel --lang ch

[2024/06/28 21:19:02] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

Traceback (most recent call last):
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1737, in openDirDialog
    self.importDirImages(targetDirPath)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1794, in importDirImages
    self.loadFilestate(dirpath)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2590, in loadFilestate
    states = f.readlines()
  File "E:\anaconda3\envs\paddlepaddle\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 3044: invalid continuation byte

```

**Comment by GreatV** [comment]
paddleocr的版本是多少, 建议使用main、或者 2.6

**Comment by Unlicensed-driver-ljx** [comment]
img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3

**Comment by GreatV** [comment]
@Unlicensed-driver-ljx 可以看下这里
- https://github.com/PFCCLab/PPOCRLabel/issues/19#issuecomment-2180764301
