### ISSUE TITLE
KeyError: 'score'

### ISSUE THREAD

**Issue by monkeycc** [PFCCLab/PPOCRLabel#34]
python 3.10
paddleocr                 2.8.0
paddlepaddle-gpu          2.6.1
pefile                    2023.2.7
pillow                    10.4.0
pip                       24.0
PPOCRLabel                2.1.4
```

python PPOCRLabel.py --lang ch

[2024/07/17 15:03:39] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "E:\2023_Code_Paddle\PPOCRLabel-main\PPOCRLabel.py", line 3453, in <module>
    sys.exit(main())
  File "E:\2023_Code_Paddle\PPOCRLabel-main\PPOCRLabel.py", line 3448, in main
    app, _win = get_main_app(sys.argv)
  File "E:\2023_Code_Paddle\PPOCRLabel-main\PPOCRLabel.py", line 3436, in get_main_app
    win = MainWindow(
  File "E:\2023_Code_Paddle\PPOCRLabel-main\PPOCRLabel.py", line 143, in __init__
    result = self.table_ocr(
  File "D:\anaconda3\envs\ocr\lib\site-packages\paddleocr\paddleocr.py", line 855, in __call__
    res, _ = super().__call__(img, return_ocr_result_in_table, img_idx=img_idx)
  File "D:\anaconda3\envs\ocr\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 172, in __call__
    "score": region["score"],
KeyError: 'score'
```

**Comment by GreatV** [comment]
这个main branch已经修复了

**Comment by GreatV** [comment]
可以拉一下release/2.8自己从源代码安装

**Comment by monkeycc** [comment]
就是下载的 main 版
release/2.8 没看到 
只有main

**Comment by GreatV** [comment]
是不是没有更新代码，同步一下代码再看看。

**Comment by GreatV** [comment]
卸载掉以前的，再安装

**Comment by YUECHE77** [comment]
你好，我也遇到了这个问题。

请问解决了吗？

我用的也是main branch

而且也只有这一个branch可供我们下载呀

**Comment by GreatV** [comment]
哦，我说的是paddleocr的main branch

**Comment by YUECHE77** [comment]
> 哦，我说的是paddleocr的main branch

请问意思是我们要把PPOCRLabel clone下来后放在paddleocr (下载的main branch) 的根目录下吗？

**Comment by YUECHE77** [comment]
放在paddleocr下面还是会报一样的错呀：

(paddleocr) D:\PaddleOCR\PPOCRLabel>python PPOCRLabel.py --lang ch
[2024/07/17 16:28:28] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 3453, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 3448, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 3436, in get_main_app
    win = MainWindow(
  File "PPOCRLabel.py", line 143, in __init__
    result = self.table_ocr(
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\paddleocr.py", line 855, in __call__
    res, _ = super().__call__(img, return_ocr_result_in_table, img_idx=img_idx)
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 172, in __call__
    "score": region["score"],
KeyError: 'score'

paddleocr我是昨天才刚刚下载的，下载的就是main branch

**Comment by GreatV** [comment]
@YUECHE77 你是怎么安装的，通过什么方式

**Comment by YUECHE77** [comment]
> @YUECHE77 你是怎么安装的，通过什么方式

不好意思，github似乎没给我发邮件，我才刚刚看到您的回复。

我就是用的git clone安装的呀：
git clone https://github.com/PaddlePaddle/PaddleOCR.git

我看paddleocr默认的branch就是main

**Comment by YUECHE77** [comment]
> @YUECHE77 你是怎么安装的，通过什么方式

我刚才又重新下载了PaddleOCR和PPOCRLabel的main branch的zip文件，然后进行解压。

但还是不行，会报一样的错误：

(paddleocr) D:\PaddleOCR-main\PPOCRLabel-main>python PPOCRLabel.py --lang ch
[2024/07/18 09:22:47] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 3453, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 3448, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 3436, in get_main_app
    win = MainWindow(
  File "PPOCRLabel.py", line 143, in __init__
    result = self.table_ocr(
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\paddleocr.py", line 855, in __call__
    res, _ = super().__call__(img, return_ocr_result_in_table, img_idx=img_idx)
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 172, in __call__
    "score": region["score"],
KeyError: 'score'

**Comment by GreatV** [comment]
@YUECHE77 你更新一下新版本PaddleOCR吧，昨天release2.8.1应该修复了

**Comment by GreatV** [comment]
@YUECHE77 要安装一下才行，不然用的还是以前的版本。

**Comment by YUECHE77** [comment]
> @YUECHE77 要安装一下才行，不然用的还是以前的版本。

我下载了2.8.1，仍然会报错。

您说的“安装一下”是什么意思嘞？像我这样用git clone 或者下载.zip文件再解压不叫安装吗？我还需要做些别的步骤嘛？

(paddleocr) D:\PaddleOCR-2.8.1\PPOCRLabel-main>python PPOCRLabel.py --lang ch
[2024/07/18 09:31:53] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 3453, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 3448, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 3436, in get_main_app
    win = MainWindow(
  File "PPOCRLabel.py", line 143, in __init__
    result = self.table_ocr(
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\paddleocr.py", line 855, in __call__
    res, _ = super().__call__(img, return_ocr_result_in_table, img_idx=img_idx)
  File "D:\anaconda3\envs\paddleocr\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 172, in __call__
    "score": region["score"],
KeyError: 'score'

**Comment by GreatV** [comment]
pip install

**Comment by YUECHE77** [comment]
感谢！可算打开了！
<img width="599" alt="image" src="https://github.com/user-attachments/assets/8f873cdc-ff52-47bc-9345-3b99defa3c8d">

过程中还遇到了“Could not locate zlibwapi.dll. Please make sure it is in your library path!”的报错，google一下就能找到教程，跟着走就完事了。
